# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
