# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 13:41
from __future__ import unicode_literals

import capstone.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(through='capstone.DeptEmp', to='capstone.Departments'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, storage=capstone.models.LocalFileSystemStorage(), upload_to=capstone.models.upload_path_handler),
        ),
    ]
