# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20170913_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='departments', through='capstone.DeptEmp', to='capstone.Departments'),
        ),
    ]
